apiVersion: v1
kind: ConfigMap
metadata:
  name: book-native-config
data:
  application.yml: |
    demo:
      message: Welcome to the native bookshop on Knative!
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 15s
    management:
      endpoints:
        web:
          exposure:
            include: health
