apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: book-service
spec:
  template:
    spec:
      containers:
        - name: book-service
          # Use ghcr.io/thomasvitale/k8s-java/book-service on AMD64
          image: ghcr.io/thomasvitale/k8s-java/book-service-arm64
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: book-config
